changelog:
  categories:
    - title: 🐛 Bug 修复
      labels:
        - fix
    - title: 🚀 新功能
      labels:
        - feat
    - title: 🔧 重构与优化
      labels:
        - refactor
    - title: 🛠 构建与依赖更新
      labels:
        - build