name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*-*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -B -V

      - name: Determine if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" == *"DEV" ]] || [[ "${{ github.ref_name }}" == *"BETA" ]] || [[ "${{ github.ref_name }}" == *"TEST" ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: List target directory
        run: ls -l Hearthstone-Script/target/

      - name: Calculate SHA256
        run: |
          cd Hearthstone-Script/target/
          sha256sum hs-script_${{ github.ref_name }}.jar > hs-script_${{ github.ref_name }}.jar.sha256
          cat hs-script_${{ github.ref_name }}.jar.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          name: hs-script_${{ github.ref_name }}
          body: ${{ steps.get_commit.outputs.message }}
          prerelease: ${{ env.prerelease }}
          files: |
            Hearthstone-Script/target/hs-script_${{ github.ref_name }}.zip
            Hearthstone-Script/target/hs-script_${{ github.ref_name }}.jar
            Hearthstone-Script/target/hs-script_${{ github.ref_name }}.jar.sha256
        env:
          GITHUB_TOKEN: ${{ github.token }}